# Travis CI configuration for coverage testing

# https://docs.travis-ci.com/user/reference/windows/
os: windows
language: shell

# https://en.wikipedia.org/wiki/MSBuild
# https://community.chocolatey.org/packages
before_install:
  # https://community.chocolatey.org/packages/netfx-4.7.2-devpack
  - choco install netfx-4.7.2-devpack
  # https://community.chocolatey.org/packages/visualstudio2019buildtools
  - choco install visualstudio2019buildtools
  - export PATH='/C/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/MSBuild/Current/Bin':$PATH
  - echo $PATH
  - MSBuild.exe -version

# Update all the things!
install:
  # https://git-scm.com/book/en/v2/Git-Tools-Submodules
  - git submodule update --init --recursive
  - git status

# Build all the things!
script:
  - cd ${TRAVIS_BUILD_DIR}
  - git submodule foreach 'MSBuild.exe *.sln -target:Build || echo Build FAILED'

# after_success:
#   - cd ${TRAVIS_BUILD_DIR}
#   - echo "Automated build and testing completed!"
